/* Main.c file generated by New Project wizard
 *
 * Created:   Thu Oct 7 2021
 * Processor: AT89C51RD2
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>

void main(void)
 { 
   // Write your code here
   while (1)
      ;
 }