/* Main.c file generated by New Project wizard
 *
 * Created:   Mon Mar 21 2022
 * Processor: AT89C51RD2
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>

void main(void)
 { 
   // Write your code here
   while (1)
      ;
 }